### PR TITLE
Add conda-forge as a dependency

### PR DESCRIPTION
**Pull request by pradal**
Close issue #93

### CODE REVIEW

**Comment by pradal** [comment]
@cyrillemidingoyi 
Tests in test/Tutorial fail

**Comment by cyrillemidingoyi** [comment]
I will make pull requests and check it.

**Comment by pradal** [comment]
I have already fix CI. But the test fail. If you want, we can merge this PR or you can work on it directly.

**Comment by cyrillemidingoyi** [comment]
Yes, we can merge this PR.

**Comment by cyrillemidingoyi** [comment]
@pradal 
Tests in test/Tutorial works now

**Comment by pradal** [comment]
Nice.

**Pull request merged**
